title: Rhys Powell
email: rhys@rpowell.me
description: >
  Posts on JavaScript, old video games, and whatever else.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://words.extremely.online" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: rhysforyou
github_username:  rpowelll

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-gist

collections:
  old_posts:
    permalink: /:collection/:title
    output: true
  links:
    permalink: /:collection/:title
    output: true

defaults:
  - scope:
      type: links
    values:
      layout: link
      master: true
      author:
        name: Rhys Powell
        email: rhys@rpowell.me
        uri: https://twitter.com/rhysforyou
  - scope:
      type: posts
    values:
      layout: post
      master: true
      author:
        name: Rhys Powell
        email: rhys@rpowell.me
        uri: https://twitter.com/rhysforyou
  - scope:
      type: old_posts
    values:
      layout: post
      master: false
