# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Rhys Powell
description:      'University student and iOS / web developer from Wollongong, Australia'
url:              http://rpowell.me

author:
  name:           'Rhys Powell'
  url:            https://rpowell.me

paginate:         5

redcarpet:
  extensions: [smart]

# Custom vars
social:
  github:         rpowelll
  twitter:        LividOcelot
  tumblr:         rpowelll
