title: Rhys Powell
email: rhys@powell.zone
description: Posts on JavaScript, Swift, computing history, and whatever else interests me.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://rpowell.me" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: rhysforyou
github_username:  rhysforyou

# Build settings
include: [".well-known"]
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-gist

collections:
  old_posts:
    permalink: /old/:categories/:year/:month/:day/:title/
    output: true
  links:
    permalink: /:categories/:year/:month/:day/:title/
    output: true

sass:
  load_paths:
    - assets/

defaults:
  - scope:
      type: posts
    values:
      layout: post
      master: true
      author:
        name: Rhys Powell
        email: rhys@rpowell.me
        uri: https://twitter.com/rhysforyou
  - scope:
      type: old_posts
    values:
      layout: post
      master: false
