# Dependencies
markdown: kramdown

# Permalinks
permalink: pretty

# Setup
title: Subspace
description: > # this means to ignore newlines until "baseurl:"
  A blog about games, programming, and whatever else by Rhys Powell
baseurl: "" # the subpath of your site, e.g. /blog/
url: http://rpowell.me

author:
  name: Rhys Powell
  url: https://rpowell.me

paginate: 5

# Custom vars
social:
  github:         rpowelll
  twitter:        powellelogram
